# Numpy data structures

When we looked at python data structures, it was obvious that the only way to deal with arrays of values (matrices / vectors etc) would be via lists and lists of lists.

This is slow and inefficient in both execution and writing code. 

`Numpy` attempts to fix this.

In [1]:
import numpy as np

## This is a list of everything in the module
np.__all__

['ModuleDeprecationWarning',
 'VisibleDeprecationWarning',
 '__version__',
 'show_config',
 'char',
 'rec',
 'memmap',
 'newaxis',
 'ndarray',
 'flatiter',
 'nditer',
 'nested_iters',
 'ufunc',
 'arange',
 'array',
 'zeros',
 'count_nonzero',
 'empty',
 'broadcast',
 'dtype',
 'fromstring',
 'fromfile',
 'frombuffer',
 'where',
 'argwhere',
 'copyto',
 'concatenate',
 'fastCopyAndTranspose',
 'lexsort',
 'set_numeric_ops',
 'can_cast',
 'promote_types',
 'min_scalar_type',
 'result_type',
 'isfortran',
 'empty_like',
 'zeros_like',
 'ones_like',
 'correlate',
 'convolve',
 'inner',
 'dot',
 'outer',
 'vdot',
 'roll',
 'rollaxis',
 'moveaxis',
 'cross',
 'tensordot',
 'little_endian',
 'fromiter',
 'array_equal',
 'array_equiv',
 'indices',
 'fromfunction',
 'isclose',
 'isscalar',
 'binary_repr',
 'base_repr',
 'ones',
 'identity',
 'allclose',
 'compare_chararrays',
 'putmask',
 'flatnonzero',
 'Inf',
 'inf',
 'infty',
 'Infinity',
 'nan',
 'NaN',
 'False_',
 'True_',
 'bitwise_not',


In [2]:
an_array = np.array([0,1,2,3,4,5,6], dtype=np.float)

print (an_array)
print( type(an_array))
help(an_array)

[0. 1. 2. 3. 4. 5. 6.]
<class 'numpy.ndarray'>
Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |

/usr/share/miniconda3/envs/jupyter/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [3]:
print(an_array.dtype)
print(an_array.shape)

float64
(7,)


In [4]:
A = np.zeros((4,4))
print (A)

print (A.shape)
print (A.diagonal())

A[0,0] = 2.0
print (A)

np.fill_diagonal(A, 1.0)
print (A)

B = A.diagonal()
B[0] = 2.0

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[0. 0. 0. 0.]
[[2. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


ValueError: assignment destination is read-only

In [5]:
for i in range(0,A.shape[0]):
    A[i,i] = 1.0
print (A)
print()

A[:,2] = 2.0
print (A)
print()

A[2,:] = 4.0
print (A)
print()

print (A.T)
print()

A[...] = 0.0
print (A)
print()

for i in range(0,A.shape[0]):
    A[i,:] = float(i)
    
print (A)
print()

for i in range(0,A.shape[0]):
    A[i,:] = i
    
print (A)
print()

print (A[::2,::2] )


print (A[::-1,::-1])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 2. 0.]
 [0. 1. 2. 0.]
 [0. 0. 2. 0.]
 [0. 0. 2. 1.]]

[[1. 0. 2. 0.]
 [0. 1. 2. 0.]
 [4. 4. 4. 4.]
 [0. 0. 2. 1.]]

[[1. 0. 4. 0.]
 [0. 1. 4. 0.]
 [2. 2. 4. 2.]
 [0. 0. 4. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]

[[0. 0.]
 [2. 2.]]
[[3. 3. 3. 3.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]]


## Speed

In [6]:
%%timeit

B = np.zeros((1000,1000))
for i in range(0,1000):
    for j in range(0,1000):
        B[i,j] = 2.0
        
        

156 ms ± 5.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%%timeit

B = np.zeros((1000,1000))
B[:,:] = 2.0

846 µs ± 18 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%%timeit

B = np.zeros((1000,1000))
B[...] = 2.0

838 µs ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Views of the data (are free)

It costs very little to look at data in a different way (e.g. to view a 2D array as a 1D vector).

Making a copy is a different story

In [9]:
print( A.reshape((2,8)))
print()

print( A.reshape((-1)))
print( A.ravel())
print()

print( A.reshape((1,-1)))
print()

[[0. 0. 0. 0. 1. 1. 1. 1.]
 [2. 2. 2. 2. 3. 3. 3. 3.]]

[0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]
[0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]

[[0. 0. 0. 0. 1. 1. 1. 1. 2. 2. 2. 2. 3. 3. 3. 3.]]



In [10]:
%%timeit 

A.reshape((1,-1))

333 ns ± 6.16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
%%timeit

elements = A.shape[0]*A.shape[1]
B = np.empty(elements)
B[...] = A[:,:].reshape(elements)

2.25 µs ± 56.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
%%timeit

elements = A.shape[0]*A.shape[1]
B = np.empty(elements)

for i in range(0,A.shape[0]):
    for j in range(0,A.shape[1]):
        B[i+j*A.shape[1]] = A[i,j]

8.56 µs ± 92.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


__Exercise:__ Try this again for a 10000x10000 array

## Indexing / broadcasting

In numpy, we can index an array by explicitly specifying elements, by specifying slices, by supplying lists of indices (or arrays), we can also supply a boolean array of the same shape as the original array which will select / return an array of all those entries where `True` applies.

Although some of these might seem difficult to use, they are often the result of other numpy operations. For example `np.where` converts a truth array to a list of indices.

In [13]:
AA = np.zeros((100,100))

AA[10,11] = 1.0
AA[99,1]  = 2.0

cond = np.where(AA >= 1.0)
print (cond)
print (AA[cond])
print (AA[ AA >= 1])
print(AA>=1.0)

(array([10, 99]), array([11,  1]))
[1. 2.]
[1. 2.]
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False  True False ... False False False]]


---

Broadcasting is a way of looping on arrays which have "compatible" but unequal sizes.

For example, the element-wise multiplication of 2 arrays

```python
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0]) 
print a * b
```
has an equivalent:

```python
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0]) 
print a * b
```

or 

```python
a = np.array([1.0, 2.0, 3.0])
b = 2.0 
print a * b
```

in which the "appropriate" interpretation of `b` is made in each case to achieve the result.

In [14]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0]) 

print( a * b)

b = np.array([2.0]) 

print (a * b)
print (a * 2.0)

[2. 4. 6.]
[2. 4. 6.]
[2. 4. 6.]


Arrays are compatible as long as each of their dimensions (shape) is either equal to the other or 1. 

Thus, above, the multplication works when `a.shape` is `(1,3)` and `b.shape` is either `(1,3)` or `(1,1)`

(Actually, these are `(3,)` and `(1,)` in the examples above ...

In [15]:
print (a.shape)
print (b.shape)
print ((a*b).shape)
print ((a+b).shape)


aa = a.reshape(1,3)
bb = b.reshape(1,1)

print (aa.shape)
print (bb.shape)
print ((aa*bb).shape)
print ((aa+bb).shape)

(3,)
(1,)
(3,)
(3,)
(1, 3)
(1, 1)
(1, 3)
(1, 3)


In multiple dimensions, the rule applies but, perhaps, is less immediately intuitive:

In [16]:
a = np.array([[ 0.0, 0.0, 0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])
b = np.array([[1.0,2.0,3.0]])
print (a + b)
print ()
print (a.shape)
print (b.shape)
print ((a+b).shape)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]

(4, 3)
(1, 3)
(4, 3)


Note that this also works for

In [17]:
a = np.array([[ 0.0, 0.0, 0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])

b = np.array([1.0,2.0,3.0])
print (a + b)
print ()
print (a.shape)
print (b.shape)
print ((a+b).shape)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]

(4, 3)
(3,)
(4, 3)


But not for

In [18]:
a = np.array([[ 0.0, 0.0, 0.0],
              [10.0,10.0,10.0],
              [20.0,20.0,20.0],
              [30.0,30.0,30.0]])

b = np.array([[1.0],[2.0],[3.0]])

print (a.shape)
print (b.shape)
print ((a+b).shape)

(4, 3)
(3, 1)


ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 

## Vector Operations

In [19]:
X = np.arange(0.0, 2.0*np.pi, 0.0001)

In [20]:
print (X)

[0.0000e+00 1.0000e-04 2.0000e-04 ... 6.2829e+00 6.2830e+00 6.2831e+00]


In [21]:
import math

math.sin(X)

TypeError: only size-1 arrays can be converted to Python scalars

In [22]:
np.sin(X)

array([ 0.00000000e+00,  9.99999998e-05,  1.99999999e-04, ...,
       -2.85307176e-04, -1.85307179e-04, -8.53071795e-05])

In [23]:
S = np.sin(X)
C = np.cos(X)

In [24]:
S2 =  S**2 + C**2
print (S2)

[1. 1. 1. ... 1. 1. 1.]


In [25]:
print (S2 - 1.0)

[ 0.00000000e+00  0.00000000e+00  2.22044605e-16 ...  0.00000000e+00
  0.00000000e+00 -1.11022302e-16]


In [26]:
test = np.isclose(S2,1.0)
print (test)

[ True  True  True ...  True  True  True]


In [27]:
print (np.where(test == False))
print (np.where(S2 == 0.0))

(array([], dtype=int64),)
(array([], dtype=int64),)


---

__Exercise__: find out how long it takes to compute the sin, sqrt, power of a 1000000 length vector (array). How does this speed compare to using the normal `math` functions element by element in the array ? What happens if X is actually a complex array ?

__Hints:__ you might find it useful to know about:
  - `np.linspace` v `np.arange`
  - `np.empty_like` or `np.zeros_like`
  - the python `enumerate` function
  - how to write a table in markdown
  
| description     | time   | notes |
|-----------------|--------|-------|
| `np.sin`        | ?      |       |
| `math.sin`      | ?      |       |
|                 | ?      |  -    |

In [28]:
X = np.linspace(0.0, 2.0*np.pi, 10000000)
print (X.shape)

# ... 

(10000000,)


In [29]:
%%timeit
S = np.sin(X)

165 ms ± 2.15 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
%%timeit

S = np.empty_like(X)
for i, x in enumerate(X):
    S[i] = math.sin(x)
    

2.79 s ± 35.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
XX = np.ones((100,100,100))
XX.shape

(100, 100, 100)

In [32]:
%%timeit
np.sin(XX)

11.3 ms ± 62.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
%%timeit

for i in range(0,100):
    for j in range(0,100):
        for k in range(0,100):
            math.sin(XX[i,j,k])
                    

282 ms ± 3.52 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [34]:
X = np.linspace(0.0, 2.0*np.pi, 10000000)
Xj = X + 1.0j
print (Xj.shape, Xj.dtype)

(10000000,) complex128


In [35]:
%%timeit

Sj = np.sin(Xj)

827 ms ± 10.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [36]:
import cmath

In [37]:
%%timeit

Sj = np.empty_like(Xj)
for i, x in enumerate(Xj):
    Sj[i] = cmath.sin(x)
    

KeyboardInterrupt: 

__Exercise__: look through the functions below from numpy, choose 3 of them and work out how to use them on arrays of data. Write a few lines to explain what you find. 

  - `np.max` v. `np.argmax`
  - `np.where`
  - `np.logical_and`
  - `np.fill_diagonal`
  - `np.count_nonzero`
  - `np.isinf` and `np.isnan`
  
  
Here is an example: 

`np.concatenate` takes a number of arrays and glues them together. For 1D arrays this is simple:

```python

A = np.array([1.0,1.0,1.0,1.0])
B = np.array([2.0,2.0,2.0,2.0])
C = np.array([3.0,3.0,3.0,3.0])

R = np.concatenate((A,B,C))

# array([ 1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.])
```

an equivalent statement is `np.hstack((A,B,C))` but note the difference with `np.vstack((A,B,C))`

With higher dimensional arrays, the gluing takes place along one `axis`:

```python
A = np.array(([1.0,1.0,1.0,1.0],[2.0,2.0,2.0,2.0]))
B = np.array(([3.0,3.0,3.0,3.0],[4.0,4.0,4.0,4.0]))
C = np.array(([5.0,5.0,5.0,5.0],[6.0,6.0,6.0,6.0]))

R = np.concatenate((A,B,C))
print R
print
R = np.concatenate((A,B,C), axis=1)
print R

```

In [ ]:
# Test the results here 

A = np.array(([1.0,1.0,1.0,1.0],[2.0,2.0,2.0,2.0]))
B = np.array(([3.0,3.0,3.0,3.0],[4.0,4.0,4.0,4.0]))
C = np.array(([5.0,5.0,5.0,5.0],[6.0,6.0,6.0,6.0]))

R = np.concatenate((A,B,C))
print R
print
R = np.concatenate((A,B,C), axis=1)
print R